# Simulations of systematic and non-systematic batch effects {#simu}

## Mean=5,unequal variance

+ $\beta_{j} \sim N(5,1^{2})$ for $j=1,...,p$ OTUs;     
+ $\sigma_{j} \sim N(0,2^{2})$ for $j=1,...,p$ OTUs;       
+ $\beta_{ij} \sim N(\beta_{j}, \sigma_{j}^{2})$ for $i = 1,...,n$ samples.       

```{r}
## Create the simulated data
m = 50
n = 10000
nc = 1000 #negative controls without treatment effects
p = 1
k = 1
ctl = rep(FALSE, n)
ctl[1:nc] = TRUE
# treatment effect
X = matrix(c(rep(0,floor(m/2)), rep(1,ceiling(m/2))), m, p)
beta = matrix(rnorm(p*n,5,1), p, n) #treatment coefficients
beta[,ctl] = 0
# batch effect
W = as.matrix(rep(0,m),m,k)
W[c(1:12,38:50),1] =  1
alpha = matrix(rnorm(k*n,5,1),k,n)
Y_alpha = sapply(alpha, function(alpha){rnorm(m, mean =  alpha, abs(rnorm(1, mean = 0, sd = 2)))})
YY_alpha = apply(Y_alpha,2,function(x){x*W})

epsilon = matrix(rnorm(m*n,0,1),m,n)
Y = X%*%beta + YY_alpha + epsilon


# estimate batch coefficient for each OTU
w.cof = c()
for(i in 1:ncol(Y)){
  res = lm(Y[,i] ~ X + W)
  sum.res = summary(res)
  w.cof[i] = sum.res$coefficients[3,1]
}

par(mfrow=c(2,2))
hist(w.cof,col = 'gray')
plot(density(w.cof))
qqnorm(w.cof)
qqline(w.cof, col='red')
par(mfrow=c(1,1))
```

## Mean=0&5,unequal variance

+ $\beta_{t} \sim N(0,1^{2})$ and $\beta_{k} \sim N(5,1^{2})$ for $t=1,...,T$ OTUs, $k=1,...,K$ OTUs and $T=\frac{3}{4}p$, $K=\frac{1}{4}p$;     
+ $\sigma_{j} \sim N(0,2^{2})$ for $j=1,...,p$ OTUs;       
+ $\beta_{ij} \sim N(\beta_{j}, \sigma_{j}^{2})$ for $i = 1,...,n$ samples.       

```{r}

## Create the simulated data
m = 50
n = 10000
nc = 1000 #negative controls without treatment effects
p = 1
k = 1
ctl = rep(FALSE, n)
ctl[1:nc] = TRUE
# treatment effect
X = matrix(c(rep(0,floor(m/2)), rep(1,ceiling(m/2))), m, p)
beta = matrix(rnorm(p*n,5,1), p, n) #treatment coefficients
beta[,ctl] = 0
# batch effect
W = as.matrix(rep(0,m),m,k)
W[c(1:12,38:50),1] =  1
alpha2 = matrix(sample(c(rnorm(k*(3*n/4),0,1),rnorm(k*(n/4),5,1)),n),k,n)
Y_alpha2 = sapply(alpha2, function(alpha){rnorm(m, mean =  alpha, sd = abs(rnorm(1, mean = 0, sd = 2)) )})
YY_alpha2 = apply(Y_alpha2,2,function(x){x*W})

epsilon = matrix(rnorm(m*n,0,1),m,n)
Y2 = X%*%beta + YY_alpha2 + epsilon




w.cof2 = c()
for(i in 1:ncol(Y2)){
  res = lm(Y2[,i] ~ X + W)
  sum.res = summary(res)
  w.cof2[i] = sum.res$coefficients[3,1]
}

par(mfrow=c(2,2))
hist(w.cof2,col = 'gray')
plot(density(w.cof2))
qqnorm(w.cof2)
qqline(w.cof2, col='red')
par(mfrow=c(1,1))
```

## Sponge data

```{r}
sponge.b.cof = c()
for(i in 1:ncol(sponge.tss.clr)){
  res = lm(sponge.tss.clr[,i] ~ sponge.trt + sponge.batch)
  sum.res = summary(res)
  sponge.b.cof[i] = sum.res$coefficients[3,1]
}

par(mfrow=c(2,2))
hist(sponge.b.cof,col = 'gray')
plot(density(sponge.b.cof))
qqnorm(sponge.b.cof)
qqline(sponge.b.cof, col='red')
par(mfrow=c(1,1))
```


## AD data

```{r}
ad.b.cof = c()
ad.batch.relevel = relevel(ad.batch, '01/07/2016')
for(i in 1:ncol(ad.tss.clr)){
  res = lm(ad.tss.clr[,i] ~ ad.trt + ad.batch.relevel)
  sum.res = summary(res)
  ad.b.cof[i] = sum.res$coefficients[4,1]
}

par(mfrow=c(2,2))
hist(ad.b.cof,col = 'gray')
plot(density(ad.b.cof))
qqnorm(ad.b.cof)
qqline(ad.b.cof, col='red')
par(mfrow=c(1,1))
```
